version: "3.8"

services:
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=alinfo
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-tpachat:
    depends_on:
      - mysqlDb
    image: raniawachene/tpachat-backend:68
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqlDb:3306/alinfo?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

  frontend:
    image: raniawachene/tpachat-frontend:latest
    depends_on:
      - app-tpachat
    restart: on-failure
    ports:
      - "80:80"

volumes:
  db:
